### ISSUE TITLE
Confusion about the proposed event super resolution.

### ISSUE THREAD

**Issue by rfww** [Lqm26/BMCNet-ESR#2]
Thanks for your work. 
As shown in Sec. 3.1, three steps are included in the event data super-resolution (1. event representation, 2. representation super-resolution, and 3. event stream recovering). However, the MSE loss function is adopted in Sec. 3.4 to measure the difference between two event count images. How do you convert the event stream from this event representation? 
If only upsample the event representation, what is the difference between the event super-resolution and image super-resolution?

**Comment by Lqm26** [comment]
Like the previous work, we can using random resample to obtain the event stream, but the timestamps of events cannot fully recovered . The difference between event super-resolution and image super-resolution can be summarized in three points: 
(1) the data format is different. Event count images are sparse, which makes the traditional image super-resolution methods, such as SRFBN, RLSP, and RSTT used in our comparison, potentially ineffective.
(2) Event streams includes both positive and negative events, each with unique distribution characteristics. This necessitates the design of specialized modules and networks.
(3) Event stream contain noise, and it's essential to mitigate the impact of the noise during super-resolusion.

**Comment by rfww** [comment]
Yeah, the format difference is a significant obstacle to directly adopting any image-based techniques to process event streams. However, if you convert them into frame-like representations first and then only upsample the corresponding representations, the aforementioned three points are not reasonable. My main concern is the lack of event stream recovery illustrated by you in Sec. 3.1.

**Comment by Lqm26** [comment]
The resampled event stream cannot be farely comparing due to the loss of the timestamps, so we chose to compare them using event count image. Additionally, another method of comparison is to evaluate their performance in downstream tasks such as Object Recognition and video reconstruction (section 4.4).

**Comment by rfww** [comment]
Exactly, the lost timestamps cannot be recovered when the event stream has been represented. That's why I always ask you for the third point illustrated in Sec. 3.1.

**Comment by Lqm26** [comment]
The timestamps can be partially recovered. For example, we can assign a time interval to each event count images and randomly resample events within this interval. In this way, we can generate a timestamp for each event. These timestamps are random within an event count image, they maintain an order between event count images.

**Comment by rfww** [comment]
These recovered timestamps are fake counterparts, which would cause catastrophic results when adopting EST as the event representation method. The upsampled event stream is still not generated.

**Comment by Lqm26** [comment]
In practice, you can mitigate this impact by using a small time interval (e.g.,10 ms) and limiting the numbers for each event count image. Additionally, this super-resolution method may be more sutilable for the tasks that use event count images, such as object recognition, classification, and tracking.

**Comment by rfww** [comment]
Thanks for your quick reply. I think you already know my main concern in the aforementioned comments. The problem formulation is different from your implementation instead of its applications. In image super-resolution, there's no one would only upsample the converted tensors without rendering the images, same for the event stream.

**Comment by Lqm26** [comment]
Thanks for your question. We have attempted to visualize the high-resolution resampled event stream. However, the event stream was too dense to discern the detailed differences. As a result, we opted to use the event count images for quantitative and qualitative comparisons. Therefore,we believe that our formulation in the paper is appropriate.

**Comment by rfww** [comment]
The event count image is not the quantitative medium in your paper, instead of the original input and output samples.

**Comment by Lqm26** [comment]
The event count image serves as the quantitative medium (see Section 3.4). And they are used as input and output samples too.
